### ISSUE TITLE
assert out_trans.shape == sess.graph.get_tensor_by_name(n_org.name+':0').shape raise AssertionError

### ISSUE THREAD

**Issue by hot-dog** [paulbauriegel/tensorflow-tools#2]
Hi! I am trying to convert pytroch model to tflight and encounter the data format mismatch problem between pytorch and tflight. Then i find this script and it is great job. But when i apply this script to my pb file, i meet some errors, it fails at line"assert out_trans.shape == sess.graph.get_tensor_by_name(n_org.name+':0').shape", i print some intermediate tensors' shape as follows:
sess.graph.get_tensor_by_name(n_org.inputs[0].name): Tensor("split_1:0", shape=(1, 3, 226, 226), dtype=float32)
sess.graph.get_tensor_by_name(n_org.inputs[1].name): Tensor("split:0", shape=(3, 3, 3, 32), dtype=float32)
sess.graph.get_tensor_by_name(n_org.name+':0').shape: (1, 32, 112, 112)
info: Conv2D convolution [<tf.Tensor 'split_1:0' shape=(1, 3, 226, 226) dtype=float32>, <tf.Tensor 'split:0' shape=(3, 3, 3, 32) dtype=float32>] s: "NCHW"
out_tens.shape: (1, 224, 112, 32)
out_trans.shape: (1, 32, 224, 112)
the out_trans shape is strange, its H is not equal with W.
Could you give some hint where is worng? thx in advance!

**Comment by paulbauriegel** [comment]
I suppose there is some bug/unhandled case in my script. Without seeing the structure of your model, it's impossible to know what additional rule needs to be added. There was a similar issue [here](https://github.com/paulbauriegel/tensorflow-tools/issues/1#issuecomment-519975199), but your problem might be very different. If you are able to share the model, that would make bug fixing easier for me.

**Comment by hot-dog** [comment]
Problem solved followed #1 , thank you very much!

**Comment by gigadeplex** [comment]
I'm getting the same error!
out tens: Tensor("convolution_1_new:0", shape=(1, 255, 128, 128), dtype=float32)
out trans: Tensor("convolution_1_transp_out:0", shape=(1, 128, 255, 128), dtype=float32)
n_org:0 : Tensor("convolution_1:0", shape=(1, 128, 128, 128), dtype=float32)

assert out_trans.shape == sess.graph.get_tensor_by_name(n_org.name+':0').shape
AssertionError

What am I missing
