### ISSUE TITLE
'ksize' is not in OP 'Conv2v' and comes error

### ISSUE THREAD

**Issue by Lvhhhh** [paulbauriegel/tensorflow-tools#7]
if n_org.type in ['MaxPool', 'AvgPool', 'Conv2D']:
            #kl = atts['ksize'].list.i # there is no ksize in atts and i dont know the reason , so froze it 3
            kl = atts['ksize'].list.i
            ksl = [kl[0], kl[2], kl[3], kl[1]]
            st = atts['strides'].list.i
            stl = [st[0], st[2], st[3], st[1]]
            atts['ksize'] = tf.AttrValue(list=tf.AttrValue.ListValue(i=ksl))
            atts['strides'] = tf.AttrValue(list=tf.AttrValue.ListValue(i=stl))
            atts = {key:n_org.node_def.attr[key] for key in list(n_org.node_def.attr.keys()) if key != 'data_format'}

but 'ksize' is not in OP 'Conv2d' and comes error
Op 'Conv2d' just has 'dilations' , "strides","padding"else but dont have "ksize" 
my tensorflow is 1.14.0

**Comment by paulbauriegel** [comment]
Ok, I will commit a fix in a second. Thanks for reporting!
