### ISSUE TITLE
Error when using your convert-onnx-to-tflite.py script.

### ISSUE THREAD

**Issue by luan1412167** [paulbauriegel/tensorflow-tools#9]
Hi there,
Thanks for your useful repo ,
I'm facing an error when using your convert-onnx-to-tflite.py script. 
This is the following error
![image](https://user-images.githubusercontent.com/37315746/94129559-b3457300-fe85-11ea-8280-6222994d716d.png)

This is my onnx model
[https://drive.google.com/file/d/1AaA0DG9X8tYAPjzi_hR0wz0F0s7-tdGx/view?usp=sharing](https://drive.google.com/file/d/1AaA0DG9X8tYAPjzi_hR0wz0F0s7-tdGx/view?usp=sharing)
my pytorch model [https://drive.google.com/file/d/18NMAcPh2ZJwaWZZ-JxvZZOWOllskygSq/view?usp=sharing](https://drive.google.com/file/d/18NMAcPh2ZJwaWZZ-JxvZZOWOllskygSq/view?usp=sharing)
You can understand precisely the error at the link [https://github.com/onnx/onnx-tensorflow/issues/767#issue-707809157](https://github.com/onnx/onnx-tensorflow/issues/767#issue-707809157) 

Sorry for my noob and highly appreciated for your support

**Comment by paulbauriegel** [comment]
I will check, but I cannot promise anything

**Comment by luan1412167** [comment]
> I will check, but I cannot promise anything

Hi @paulbauriegel ,
I have studied several days for the issue but can't fix it. Do you have any update?

**Comment by luan1412167** [comment]
I have just converted to keras NHWC and convert to tflite successfully. Thanks
